// SPDX-License-Identifier: Apache-2.0
// © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
#![allow(clippy::panic)]
//! Workspace crossing from the CDDL-admitted generated corpus to the
//! publishable verifier crate's package-local semantic resources.

#[test]
fn verifier_package_resources_equal_the_checked_generated_corpus() {
    let pairs: &[(&str, &[u8], &[u8])] = &[
        (
            "authority-facts.echo-dpo.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/authority-facts.echo-dpo.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/primary/authority-facts.echo-dpo.cbor"
            ),
        ),
        (
            "authority-facts.echo-lawpack.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/authority-facts.echo-lawpack.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/primary/authority-facts.echo-lawpack.cbor"
            ),
        ),
        (
            "generated-artifact-profile.echo-dpo-registration.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/generated-artifact-profile.echo-dpo-registration.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/primary/generated-artifact-profile.echo-dpo-registration.cbor"
            ),
        ),
        (
            "lawpack.echo-dpo.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/lawpack.echo-dpo.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/primary/lawpack.echo-dpo.cbor"
            ),
        ),
        (
            "resource.lawpack-exports.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.lawpack-exports.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.lawpack-exports.cbor"
            ),
        ),
        (
            "resource.lawpack-target-adapter.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.lawpack-target-adapter.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.lawpack-target-adapter.cbor"
            ),
        ),
        (
            "resource.lawpack-verifier.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.lawpack-verifier.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.lawpack-verifier.cbor"
            ),
        ),
        (
            "resource.target-intrinsics.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-intrinsics.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-intrinsics.cbor"
            ),
        ),
        (
            "resource.target-footprint-algebra.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-footprint-algebra.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-footprint-algebra.cbor"
            ),
        ),
        (
            "resource.target-cost-algebra.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-cost-algebra.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-cost-algebra.cbor"
            ),
        ),
        (
            "resource.target-obstruction-taxonomy.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-obstruction-taxonomy.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-obstruction-taxonomy.cbor"
            ),
        ),
        (
            "resource.target-operation-profiles.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-operation-profiles.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-operation-profiles.cbor"
            ),
        ),
        (
            "resource.target-verifier-contract.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-verifier-contract.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-verifier-contract.cbor"
            ),
        ),
        (
            "resource.target-ir.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/resource.target-ir.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/resources/resource.target-ir.cbor"
            ),
        ),
        (
            "target-profile.echo-dpo.cbor",
            include_bytes!(
                "../../../crates/echo-edict-provider-verifier/resources/target-profile.echo-dpo.cbor"
            ),
            include_bytes!(
                "../../../schemas/edict-provider/generated/v1/primary/target-profile.echo-dpo.cbor"
            ),
        ),
    ];

    for (name, packaged, generated) in pairs {
        assert_eq!(packaged, generated, "semantic resource drift: {name}");
    }
}
