#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
OUT_FILE="$DOCS_DIR/echo-total.md"

priority=(
  "docs-index.md"
  "architecture-outline.md"
  "execution-plan.md"
  "decision-log.md"
)

declare -A seen

{
  echo "# Echo Total Documentation Rollup"
  echo
  echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo
  echo "> This file is generated by scripts/gen-echo-total.sh. Edit source docs under docs/, not this rollup."
  echo
  echo "---"

  # Priority files first, if present
  for p in "${priority[@]}"; do
    f="$DOCS_DIR/$p"
    if [[ -f "$f" ]]; then
      seen["$f"]=1
      echo
      echo "\n\n# File: $p"
      echo
      cat "$f"
      echo
      echo "\n---"
    fi
  done

  # Then all other Markdown files at top-level docs/, alphabetically
  while IFS= read -r -d '' f; do
    [[ ${seen["$f"]+x} ]] && continue
    base="$(basename "$f")"
    [[ "$base" == "echo-total.md" ]] && continue
    echo
    echo "\n\n# File: $base"
    echo
    cat "$f"
    echo
    echo "\n---"
  done < <(find "$DOCS_DIR" -maxdepth 1 -type f -name "*.md" -print0 | sort -z)
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"

