.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH echo-cli-inspect 1  "echo-cli-inspect "
.SH NAME
echo\-cli\-inspect \- Inspect a WSC snapshot
.SH SYNOPSIS
\fBecho\-cli\-inspect\fR [\fB\-\-tree\fR] [\fB\-\-raw\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISNAPSHOT\fR>
.SH DESCRIPTION
Inspect a WSC snapshot
.SH OPTIONS
.TP
\fB\-\-tree\fR
Show ASCII tree of graph structure
.TP
\fB\-\-raw\fR
Show attachment payload bytes as hex instead of decoding known payloads
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISNAPSHOT\fR>
Path to WSC snapshot file
