.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH echo-cli-wsc-causal-history-verify 1  "echo-cli-wsc-causal-history-verify "
.SH NAME
echo\-cli\-wsc\-causal\-history\-verify \- Verify a WSC causal\-history bundle without importing Echo history
.SH SYNOPSIS
\fBecho\-cli\-wsc\-causal\-history\-verify\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIBUNDLE\fR>
.SH DESCRIPTION
Verify a WSC causal\-history bundle without importing Echo history
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBUNDLE\fR>
Bundle directory to verify
