.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH verify 1  "verify " 
.SH NAME
verify \- Verify hash integrity of a WSC snapshot
.SH SYNOPSIS
\fBverify\fR [\fB\-\-expected\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISNAPSHOT\fR> 
.SH DESCRIPTION
Verify hash integrity of a WSC snapshot
.SH OPTIONS
.TP
\fB\-\-expected\fR \fI<EXPECTED>\fR
Expected state root hash (hex) to compare against
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISNAPSHOT\fR>
Path to WSC snapshot file
