.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH echo-cli-wsc-causal-history-inspect 1  "echo-cli-wsc-causal-history-inspect "
.SH NAME
echo\-cli\-wsc\-causal\-history\-inspect \- Inspect a WSC causal\-history bundle manifest and envelopes
.SH SYNOPSIS
\fBecho\-cli\-wsc\-causal\-history\-inspect\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIBUNDLE\fR>
.SH DESCRIPTION
Inspect a WSC causal\-history bundle manifest and envelopes
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBUNDLE\fR>
Bundle directory to inspect
