.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH bench 1  "bench " 
.SH NAME
bench \- Run benchmarks and format results
.SH SYNOPSIS
\fBbench\fR [\fB\-\-filter\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Run benchmarks and format results
.SH OPTIONS
.TP
\fB\-\-filter\fR \fI<FILTER>\fR
Filter benchmarks by pattern
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
