.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH inspect 1  "inspect " 
.SH NAME
inspect \- Inspect a WSC snapshot
.SH SYNOPSIS
\fBinspect\fR [\fB\-\-tree\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISNAPSHOT\fR> 
.SH DESCRIPTION
Inspect a WSC snapshot
.SH OPTIONS
.TP
\fB\-\-tree\fR
Show ASCII tree of graph structure
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISNAPSHOT\fR>
Path to WSC snapshot file
