// SPDX-License-Identifier: Apache-2.0
// © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
/**
 * TTD Generated Registry
 *
 * Auto-generated by @wesley/generator-ttd
 * DO NOT EDIT
 */

import { SchemaId } from './primitives';

/** SHA-256 hash of the source schema */
export const SCHEMA_SHA256 = 'd55d6000b43562e7be04702cdd4335452d1eb6df1f0fbea924e4c6434fff2871';

/**
 * @deprecated Use SCHEMA_SHA256 instead. Will be removed in a future version.
 */
export const SCHEMA_HASH = SCHEMA_SHA256;

/**
 * Type-safe schema identifier for this protocol version.
 * Use this for runtime schema verification instead of raw string comparison.
 */
export const SCHEMA_ID = SchemaId.fromHex(SCHEMA_SHA256);

// Type ID constants
export const CURSOR_MOVED_TYPE_ID = 1;
export const SEEK_COMPLETED_TYPE_ID = 2;
export const SEEK_FAILED_TYPE_ID = 3;
export const VIOLATION_DETECTED_TYPE_ID = 4;
export const COMPLIANCE_UPDATE_TYPE_ID = 5;
export const SESSION_STARTED_TYPE_ID = 6;
export const SESSION_ENDED_TYPE_ID = 7;
export const CURSOR_CREATED_TYPE_ID = 8;
export const CURSOR_DESTROYED_TYPE_ID = 9;

// Operation ID constants
export const STEP_FORWARD_OP_ID = 116350618;
export const GET_CURSOR_OP_ID = 639452774;
export const DESTROY_CURSOR_OP_ID = 856261846;
export const GET_PENDING_OBLIGATIONS_OP_ID = 1131058299;
export const PLAY_OP_ID = 1379835894;
export const STEP_BACK_OP_ID = 1394286172;
export const LIST_CURSORS_OP_ID = 1482350986;
export const SEEK_OP_ID = 1824277946;
export const PAUSE_OP_ID = 2364740775;
export const END_SESSION_OP_ID = 2437620378;
export const GET_VIOLATIONS_OP_ID = 3281714801;
export const CREATE_CURSOR_OP_ID = 3581082943;
export const GET_COMPLIANCE_STATUS_OP_ID = 3843805192;
export const START_SESSION_OP_ID = 4193224715;

/** Type name to ID mapping */
export const TYPE_REGISTRY = new Map<string, number>([
  ['CursorMoved', 1],
  ['SeekCompleted', 2],
  ['SeekFailed', 3],
  ['ViolationDetected', 4],
  ['ComplianceUpdate', 5],
  ['SessionStarted', 6],
  ['SessionEnded', 7],
  ['CursorCreated', 8],
  ['CursorDestroyed', 9],
]);

/** Operation name to ID mapping */
export const OP_REGISTRY = new Map<string, number>([
  ['stepForward', 116350618],
  ['getCursor', 639452774],
  ['destroyCursor', 856261846],
  ['getPendingObligations', 1131058299],
  ['play', 1379835894],
  ['stepBack', 1394286172],
  ['listCursors', 1482350986],
  ['seek', 1824277946],
  ['pause', 2364740775],
  ['endSession', 2437620378],
  ['getViolations', 3281714801],
  ['createCursor', 3581082943],
  ['getComplianceStatus', 3843805192],
  ['startSession', 4193224715],
]);

/** Type ID to name mapping */
export const TYPE_REGISTRY_REV = new Map<number, string>([
  [1, 'CursorMoved'],
  [2, 'SeekCompleted'],
  [3, 'SeekFailed'],
  [4, 'ViolationDetected'],
  [5, 'ComplianceUpdate'],
  [6, 'SessionStarted'],
  [7, 'SessionEnded'],
  [8, 'CursorCreated'],
  [9, 'CursorDestroyed'],
]);

/** Operation ID to name mapping */
export const OP_REGISTRY_REV = new Map<number, string>([
  [116350618, 'stepForward'],
  [639452774, 'getCursor'],
  [856261846, 'destroyCursor'],
  [1131058299, 'getPendingObligations'],
  [1379835894, 'play'],
  [1394286172, 'stepBack'],
  [1482350986, 'listCursors'],
  [1824277946, 'seek'],
  [2364740775, 'pause'],
  [2437620378, 'endSession'],
  [3281714801, 'getViolations'],
  [3581082943, 'createCursor'],
  [3843805192, 'getComplianceStatus'],
  [4193224715, 'startSession'],
]);

/**
 * Get type name by ID
 */
export function getTypeById(id: number): string | undefined {
  return TYPE_REGISTRY_REV.get(id);
}

/**
 * Get operation by ID
 */
export function getOpById(id: number): string | undefined {
  return OP_REGISTRY_REV.get(id);
}

/**
 * Get type ID by name
 */
export function getTypeIdByName(name: string): number | undefined {
  return TYPE_REGISTRY.get(name);
}

/**
 * Get operation ID by name
 */
export function getOpIdByName(name: string): number | undefined {
  return OP_REGISTRY.get(name);
}
