// SPDX-License-Identifier: Apache-2.0
// © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
/**
 * TTD Generated Types
 *
 * Auto-generated by @wesley/generator-ttd
 * DO NOT EDIT
 */

/**
 * CursorRole enum
 */
export enum CursorRole {
  WRITER = 'WRITER',
  READER = 'READER',
}

/**
 * PlaybackMode enum
 */
export enum PlaybackMode {
  PAUSED = 'PAUSED',
  PLAY = 'PLAY',
  STEP_FORWARD = 'STEP_FORWARD',
  STEP_BACK = 'STEP_BACK',
  SEEK = 'SEEK',
}

/**
 * SeekResult enum
 */
export enum SeekResult {
  OK = 'OK',
  OUT_OF_RANGE = 'OUT_OF_RANGE',
  DIVERGED = 'DIVERGED',
}

/**
 * ComplianceStatus enum
 */
export enum ComplianceStatus {
  COMPLIANT = 'COMPLIANT',
  VIOLATION = 'VIOLATION',
  PENDING = 'PENDING',
}

/**
 * ViolationSeverity enum
 */
export enum ViolationSeverity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  FATAL = 'FATAL',
}

/**
 * StepResultKind enum
 */
export enum StepResultKind {
  NO_OP = 'NO_OP',
  ADVANCED = 'ADVANCED',
  SEEKED = 'SEEKED',
  REACHED_FRONTIER = 'REACHED_FRONTIER',
}

/**
 * CursorMoved interface
 */
export interface CursorMoved {
  sessionId: Hash;
  cursorId: Hash;
  worldlineId: Hash;
  warpId: Hash;
  tick: number;
  commitHash: Hash;
  timestamp: Timestamp;
}

/**
 * SeekCompleted interface
 */
export interface SeekCompleted {
  sessionId: Hash;
  cursorId: Hash;
  fromTick: number;
  toTick: number;
  result: SeekResult;
  timestamp: Timestamp;
}

/**
 * SeekFailed interface
 */
export interface SeekFailed {
  sessionId: Hash;
  cursorId: Hash;
  targetTick: number;
  reason: string;
  timestamp: Timestamp;
}

/**
 * ViolationDetected interface
 */
export interface ViolationDetected {
  sessionId: Hash;
  cursorId: Hash;
  tick: number;
  violation: Violation;
  timestamp: Timestamp;
}

/**
 * ComplianceUpdate interface
 */
export interface ComplianceUpdate {
  sessionId: Hash;
  cursorId: Hash;
  tick: number;
  status: ComplianceStatus;
  violationCount: number;
  timestamp: Timestamp;
}

/**
 * SessionStarted interface
 */
export interface SessionStarted {
  sessionId: Hash;
  worldlineId: Hash;
  timestamp: Timestamp;
}

/**
 * SessionEnded interface
 */
export interface SessionEnded {
  sessionId: Hash;
  reason: string | undefined;
  timestamp: Timestamp;
}

/**
 * CursorCreated interface
 */
export interface CursorCreated {
  sessionId: Hash;
  cursorId: Hash;
  role: CursorRole;
  initialTick: number;
  timestamp: Timestamp;
}

/**
 * CursorDestroyed interface
 */
export interface CursorDestroyed {
  sessionId: Hash;
  cursorId: Hash;
  finalTick: number;
  timestamp: Timestamp;
}

/**
 * Violation interface
 * @version 1.0.0
 */
export interface Violation {
  code: string;
  severity: ViolationSeverity;
  message: string;
  channelId: string | undefined;
  tick: number | undefined;
  emissionCount: number | undefined;
}

/**
 * TruthFrame interface
 * @version 1.0.0
 */
export interface TruthFrame {
  sessionId: Hash;
  cursorId: Hash;
  worldlineId: Hash;
  warpId: Hash;
  tick: number;
  commitHash: Hash;
  channel: string;
  valueHash: Hash;
}

/**
 * ObligationState interface
 * @version 1.0.0
 */
export interface ObligationState {
  id: string;
  description: string;
  deadlineTick: number;
  status: string;
}

/**
 * StepResult interface
 */
export interface StepResult {
  result: StepResultKind;
  tick: number;
}

/**
 * Snapshot interface
 */
export interface Snapshot {
  worldlineId: Hash;
  tick: number;
}

/**
 * ComplianceModel interface
 */
export interface ComplianceModel {
  isGreen: boolean;
  violations: Violation[];
}

/**
 * Obligation interface
 */
export interface Obligation {
  id: string;
  description: string;
  deadlineTick: number;
}

/**
 * ObligationReport interface
 */
export interface ObligationReport {
  pending: Obligation[];
  satisfied: Obligation[];
  violated: Obligation[];
}

/**
 * CursorState interface
 * @version 1.0.0
 */
export interface CursorState {
  sessionId: Hash;
  cursorId: Hash;
  worldlineId: Hash;
  warpId: Hash;
  tick: number;
  commitHash: Hash;
  role: CursorRole;
  mode: PlaybackMode;
}

/**
 * TtdSystem interface
 */
export interface TtdSystem {
  _placeholder: boolean | undefined;
}

/**
 * Arguments for stepForward operation
 */
export interface StepForwardArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for getCursor operation
 */
export interface GetCursorArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for destroyCursor operation
 */
export interface DestroyCursorArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for getPendingObligations operation
 */
export interface GetPendingObligationsArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for play operation
 */
export interface PlayArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for stepBack operation
 */
export interface StepBackArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for listCursors operation
 */
export interface ListCursorsArgs {
  sessionId: Hash;
}

/**
 * Arguments for seek operation
 */
export interface SeekArgs {
  sessionId: Hash;
  cursorId: Hash;
  targetTick: number;
}

/**
 * Arguments for pause operation
 */
export interface PauseArgs {
  sessionId: Hash;
  cursorId: Hash;
}

/**
 * Arguments for endSession operation
 */
export interface EndSessionArgs {
  sessionId: Hash;
  reason: string | undefined;
}

/**
 * Arguments for getViolations operation
 */
export interface GetViolationsArgs {
  sessionId: Hash;
  fromTick: number;
  toTick: number;
}

/**
 * Arguments for createCursor operation
 */
export interface CreateCursorArgs {
  sessionId: Hash;
  role: CursorRole;
  initialTick: number | undefined;
}

/**
 * Arguments for getComplianceStatus operation
 */
export interface GetComplianceStatusArgs {
  sessionId: Hash;
  cursorId: Hash;
  tick: number;
}

/**
 * Arguments for startSession operation
 */
export interface StartSessionArgs {
  worldlineId: Hash;
}
