// SPDX-License-Identifier: Apache-2.0
// © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
/**
 * TTD Generated Zod Validators
 *
 * Auto-generated by @wesley/generator-ttd
 * DO NOT EDIT
 */

import { z } from 'zod';

/**
 * Zod schema for CursorRole
 */
export const CursorRoleSchema = z.enum(['WRITER', 'READER']);
export type CursorRole = z.infer<typeof CursorRoleSchema>;

/**
 * Zod schema for PlaybackMode
 */
export const PlaybackModeSchema = z.enum(['PAUSED', 'PLAY', 'STEP_FORWARD', 'STEP_BACK', 'SEEK']);
export type PlaybackMode = z.infer<typeof PlaybackModeSchema>;

/**
 * Zod schema for SeekResult
 */
export const SeekResultSchema = z.enum(['OK', 'OUT_OF_RANGE', 'DIVERGED']);
export type SeekResult = z.infer<typeof SeekResultSchema>;

/**
 * Zod schema for ComplianceStatus
 */
export const ComplianceStatusSchema = z.enum(['COMPLIANT', 'VIOLATION', 'PENDING']);
export type ComplianceStatus = z.infer<typeof ComplianceStatusSchema>;

/**
 * Zod schema for ViolationSeverity
 */
export const ViolationSeveritySchema = z.enum(['INFO', 'WARN', 'ERROR', 'FATAL']);
export type ViolationSeverity = z.infer<typeof ViolationSeveritySchema>;

/**
 * Zod schema for StepResultKind
 */
export const StepResultKindSchema = z.enum(['NO_OP', 'ADVANCED', 'SEEKED', 'REACHED_FRONTIER']);
export type StepResultKind = z.infer<typeof StepResultKindSchema>;

/**
 * Zod schema for CursorMoved
 */
export const CursorMovedSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  worldlineId: HashSchema,
  warpId: HashSchema,
  tick: z.number().int(),
  commitHash: HashSchema,
  timestamp: TimestampSchema,
});
export type CursorMoved = z.infer<typeof CursorMovedSchema>;

/**
 * Zod schema for SeekCompleted
 */
export const SeekCompletedSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  fromTick: z.number().int(),
  toTick: z.number().int(),
  result: SeekResultSchema,
  timestamp: TimestampSchema,
});
export type SeekCompleted = z.infer<typeof SeekCompletedSchema>;

/**
 * Zod schema for SeekFailed
 */
export const SeekFailedSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  targetTick: z.number().int(),
  reason: z.string(),
  timestamp: TimestampSchema,
});
export type SeekFailed = z.infer<typeof SeekFailedSchema>;

/**
 * Zod schema for ViolationDetected
 */
export const ViolationDetectedSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  tick: z.number().int(),
  violation: ViolationSchema,
  timestamp: TimestampSchema,
});
export type ViolationDetected = z.infer<typeof ViolationDetectedSchema>;

/**
 * Zod schema for ComplianceUpdate
 */
export const ComplianceUpdateSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  tick: z.number().int(),
  status: ComplianceStatusSchema,
  violationCount: z.number().int(),
  timestamp: TimestampSchema,
});
export type ComplianceUpdate = z.infer<typeof ComplianceUpdateSchema>;

/**
 * Zod schema for SessionStarted
 */
export const SessionStartedSchema = z.object({
  sessionId: HashSchema,
  worldlineId: HashSchema,
  timestamp: TimestampSchema,
});
export type SessionStarted = z.infer<typeof SessionStartedSchema>;

/**
 * Zod schema for SessionEnded
 */
export const SessionEndedSchema = z.object({
  sessionId: HashSchema,
  reason: z.string().nullish(),
  timestamp: TimestampSchema,
});
export type SessionEnded = z.infer<typeof SessionEndedSchema>;

/**
 * Zod schema for CursorCreated
 */
export const CursorCreatedSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  role: CursorRoleSchema,
  initialTick: z.number().int(),
  timestamp: TimestampSchema,
});
export type CursorCreated = z.infer<typeof CursorCreatedSchema>;

/**
 * Zod schema for CursorDestroyed
 */
export const CursorDestroyedSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  finalTick: z.number().int(),
  timestamp: TimestampSchema,
});
export type CursorDestroyed = z.infer<typeof CursorDestroyedSchema>;

/**
 * Zod schema for Violation
 */
export const ViolationSchema = z.object({
  code: z.string(),
  severity: ViolationSeveritySchema,
  message: z.string(),
  channelId: z.string().nullish(),
  tick: z.number().int().nullish(),
  emissionCount: z.number().int().nullish(),
});
export type Violation = z.infer<typeof ViolationSchema>;

/**
 * Zod schema for TruthFrame
 */
export const TruthFrameSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  worldlineId: HashSchema,
  warpId: HashSchema,
  tick: z.number().int(),
  commitHash: HashSchema,
  channel: z.string(),
  valueHash: HashSchema,
});
export type TruthFrame = z.infer<typeof TruthFrameSchema>;

/**
 * Zod schema for ObligationState
 */
export const ObligationStateSchema = z.object({
  id: z.string(),
  description: z.string(),
  deadlineTick: z.number().int(),
  status: z.string(),
});
export type ObligationState = z.infer<typeof ObligationStateSchema>;

/**
 * Zod schema for StepResult
 */
export const StepResultSchema = z.object({
  result: StepResultKindSchema,
  tick: z.number().int(),
});
export type StepResult = z.infer<typeof StepResultSchema>;

/**
 * Zod schema for Snapshot
 */
export const SnapshotSchema = z.object({
  worldlineId: HashSchema,
  tick: z.number().int(),
});
export type Snapshot = z.infer<typeof SnapshotSchema>;

/**
 * Zod schema for ComplianceModel
 */
export const ComplianceModelSchema = z.object({
  isGreen: z.boolean(),
  violations: z.array(ViolationSchema),
});
export type ComplianceModel = z.infer<typeof ComplianceModelSchema>;

/**
 * Zod schema for Obligation
 */
export const ObligationSchema = z.object({
  id: z.string(),
  description: z.string(),
  deadlineTick: z.number().int(),
});
export type Obligation = z.infer<typeof ObligationSchema>;

/**
 * Zod schema for ObligationReport
 */
export const ObligationReportSchema = z.object({
  pending: z.array(ObligationSchema),
  satisfied: z.array(ObligationSchema),
  violated: z.array(ObligationSchema),
});
export type ObligationReport = z.infer<typeof ObligationReportSchema>;

/**
 * Zod schema for CursorState
 */
export const CursorStateSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  worldlineId: HashSchema,
  warpId: HashSchema,
  tick: z.number().int().gte(0),
  commitHash: HashSchema,
  role: CursorRoleSchema,
  mode: PlaybackModeSchema,
});
export type CursorState = z.infer<typeof CursorStateSchema>;

/**
 * Zod schema for TtdSystem
 */
export const TtdSystemSchema = z.object({
  _placeholder: z.boolean().nullish(),
});
export type TtdSystem = z.infer<typeof TtdSystemSchema>;

/**
 * Zod schema for stepForward arguments
 */
export const StepForwardArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type StepForwardArgs = z.infer<typeof StepForwardArgsSchema>;

/**
 * Zod schema for getCursor arguments
 */
export const GetCursorArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type GetCursorArgs = z.infer<typeof GetCursorArgsSchema>;

/**
 * Zod schema for destroyCursor arguments
 */
export const DestroyCursorArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type DestroyCursorArgs = z.infer<typeof DestroyCursorArgsSchema>;

/**
 * Zod schema for getPendingObligations arguments
 */
export const GetPendingObligationsArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type GetPendingObligationsArgs = z.infer<typeof GetPendingObligationsArgsSchema>;

/**
 * Zod schema for play arguments
 */
export const PlayArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type PlayArgs = z.infer<typeof PlayArgsSchema>;

/**
 * Zod schema for stepBack arguments
 */
export const StepBackArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type StepBackArgs = z.infer<typeof StepBackArgsSchema>;

/**
 * Zod schema for listCursors arguments
 */
export const ListCursorsArgsSchema = z.object({
  sessionId: HashSchema,
});
export type ListCursorsArgs = z.infer<typeof ListCursorsArgsSchema>;

/**
 * Zod schema for seek arguments
 */
export const SeekArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  targetTick: z.number().int(),
});
export type SeekArgs = z.infer<typeof SeekArgsSchema>;

/**
 * Zod schema for pause arguments
 */
export const PauseArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
});
export type PauseArgs = z.infer<typeof PauseArgsSchema>;

/**
 * Zod schema for endSession arguments
 */
export const EndSessionArgsSchema = z.object({
  sessionId: HashSchema,
  reason: z.string().optional(),
});
export type EndSessionArgs = z.infer<typeof EndSessionArgsSchema>;

/**
 * Zod schema for getViolations arguments
 */
export const GetViolationsArgsSchema = z.object({
  sessionId: HashSchema,
  fromTick: z.number().int(),
  toTick: z.number().int(),
});
export type GetViolationsArgs = z.infer<typeof GetViolationsArgsSchema>;

/**
 * Zod schema for createCursor arguments
 */
export const CreateCursorArgsSchema = z.object({
  sessionId: HashSchema,
  role: CursorRoleSchema,
  initialTick: z.number().int().optional(),
});
export type CreateCursorArgs = z.infer<typeof CreateCursorArgsSchema>;

/**
 * Zod schema for getComplianceStatus arguments
 */
export const GetComplianceStatusArgsSchema = z.object({
  sessionId: HashSchema,
  cursorId: HashSchema,
  tick: z.number().int(),
});
export type GetComplianceStatusArgs = z.infer<typeof GetComplianceStatusArgsSchema>;

/**
 * Zod schema for startSession arguments
 */
export const StartSessionArgsSchema = z.object({
  worldlineId: HashSchema,
});
export type StartSessionArgs = z.infer<typeof StartSessionArgsSchema>;
