// SPDX-License-Identifier: Apache-2.0
// © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
// Generated by @wesley/generator-echo. Do not edit.
// Proof-slice rewrite API: capability-bounded Rust authoring surface.

pub trait ReadCounter {
    fn read_counter(&self) -> &Counter;
}

pub trait WriteCounter {
    fn write_counter(&mut self, value: Counter);
}

#[derive(Debug, Clone, PartialEq)]
pub struct IncrementCounterArgs {
    pub counter_id: String,
}

pub trait IncrementCounterContext: ReadCounter + WriteCounter {}
impl<T> IncrementCounterContext for T where T: ReadCounter + WriteCounter {}

pub trait IncrementCounterRewrite {
    type Error;

    fn apply<C>(&self, ctx: &mut C, args: IncrementCounterArgs) -> Result<Counter, Self::Error>
    where C: IncrementCounterContext;
}
