// SPDX-License-Identifier: Apache-2.0
// © James Ross Ω FLYING•ROBOTS <https://github.com/flyingrobots>
// Generated by @wesley/generator-echo. Do not edit.
// Proof-slice rewrite API: capability-bounded Rust authoring surface.

pub trait CreateBufferWorldlineCreateWorldlineSlot {
    fn create_worldline_slot(&mut self, value: BufferWorldline) -> BufferWorldline;
}

pub trait CreateBufferWorldlineCreateHeadSlot {
    fn create_head_slot(&mut self, value: RopeHead) -> RopeHead;
}

pub trait CreateBufferWorldlineCreateCheckpointSlot {
    fn create_checkpoint_slot(&mut self, value: Checkpoint) -> Checkpoint;
}

pub trait CreateBufferWorldlineCreateInitialBlobSlot {
    fn create_initial_blob_slot(&mut self, value: TextBlob) -> TextBlob;
}

pub trait CreateBufferWorldlineCreateInitialLeafSlot {
    fn create_initial_leaf_slot(&mut self, value: RopeLeaf) -> RopeLeaf;
}

pub trait CreateCheckpointReadWorldlineSlot {
    fn read_worldline_slot(&self) -> &BufferWorldline;
}

pub trait CreateCheckpointReadCurrentHeadSlot {
    fn read_current_head_slot(&self) -> &RopeHead;
}

pub trait CreateCheckpointCreateCheckpointSlot {
    fn create_checkpoint_slot(&mut self, value: Checkpoint) -> Checkpoint;
}

pub trait ReplaceRangeAsTickReadWorldlineSlot {
    fn read_worldline_slot(&self) -> &BufferWorldline;
}

pub trait ReplaceRangeAsTickWriteWorldlineSlot {
    fn write_worldline_slot(&mut self, value: BufferWorldline);
}

pub trait ReplaceRangeAsTickReadBaseHeadSlot {
    fn read_base_head_slot(&self) -> &RopeHead;
}

pub enum ReplaceRangeAsTickTouchedRopeClosureItemRef<'a> {
    RopeBranch(&'a RopeBranch),
    RopeLeaf(&'a RopeLeaf),
    TextBlob(&'a TextBlob),
}

pub trait ReplaceRangeAsTickReadTouchedRopeClosure {
    fn read_touched_rope_closure(&self) -> Vec<ReplaceRangeAsTickTouchedRopeClosureItemRef<'_>>;
}

pub enum ReplaceRangeAsTickAffectedAnchorsClosureItemRef<'a> {
    Anchor(&'a Anchor),
}

pub trait ReplaceRangeAsTickReadAffectedAnchorsClosure {
    fn read_affected_anchors_closure(&self)
        -> Vec<ReplaceRangeAsTickAffectedAnchorsClosureItemRef<'_>>;
}

pub trait ReplaceRangeAsTickCreateNewBlobSlot {
    fn create_new_blob_slot(&mut self, value: TextBlob) -> TextBlob;
}

pub trait ReplaceRangeAsTickCreateNewLeavesSlot {
    fn create_new_leaves_slot(&mut self, value: RopeLeaf) -> RopeLeaf;
}

pub trait ReplaceRangeAsTickCreateNewBranchesSlot {
    fn create_new_branches_slot(&mut self, value: RopeBranch) -> RopeBranch;
}

pub trait ReplaceRangeAsTickCreateNextHeadSlot {
    fn create_next_head_slot(&mut self, value: RopeHead) -> RopeHead;
}

pub trait ReplaceRangeAsTickCreateTickSlot {
    fn create_tick_slot(&mut self, value: Tick) -> Tick;
}

pub trait ReplaceRangeAsTickCreateReceiptSlot {
    fn create_receipt_slot(&mut self, value: TickReceipt) -> TickReceipt;
}

pub trait ReplaceRangeAsTickUpdateWorldlineCanonicalHead {
    fn update_worldline_canonical_head(&mut self, value: String);
}

#[derive(Debug, Clone, PartialEq)]
pub struct CreateBufferWorldlineArgs {
    pub input: CreateBufferWorldlineInput,
}

// CreateBufferWorldline forbidden surfaces: AstState, Diagnostics, GitWitness, UiState
pub trait CreateBufferWorldlineContext:
    CreateBufferWorldlineCreateWorldlineSlot
    + CreateBufferWorldlineCreateHeadSlot
    + CreateBufferWorldlineCreateCheckpointSlot
    + CreateBufferWorldlineCreateInitialBlobSlot
    + CreateBufferWorldlineCreateInitialLeafSlot
{
}
impl<T> CreateBufferWorldlineContext for T where
    T: CreateBufferWorldlineCreateWorldlineSlot
        + CreateBufferWorldlineCreateHeadSlot
        + CreateBufferWorldlineCreateCheckpointSlot
        + CreateBufferWorldlineCreateInitialBlobSlot
        + CreateBufferWorldlineCreateInitialLeafSlot
{
}

pub trait CreateBufferWorldlineRewrite {
    type Error;

    fn apply<C>(
        &self,
        ctx: &mut C,
        args: CreateBufferWorldlineArgs,
    ) -> Result<CreateBufferWorldlineResult, Self::Error>
    where
        C: CreateBufferWorldlineContext;
}

#[derive(Debug, Clone, PartialEq)]
pub struct CreateCheckpointArgs {
    pub input: CreateCheckpointInput,
}

// CreateCheckpoint forbidden surfaces: RopeBranch, RopeLeaf, TextBlob, Tick, TickReceipt, AstState, Diagnostics, GitWitness, UiState
pub trait CreateCheckpointContext:
    CreateCheckpointReadWorldlineSlot
    + CreateCheckpointReadCurrentHeadSlot
    + CreateCheckpointCreateCheckpointSlot
{
}
impl<T> CreateCheckpointContext for T where
    T: CreateCheckpointReadWorldlineSlot
        + CreateCheckpointReadCurrentHeadSlot
        + CreateCheckpointCreateCheckpointSlot
{
}

pub trait CreateCheckpointRewrite {
    type Error;

    fn apply<C>(&self, ctx: &mut C, args: CreateCheckpointArgs)
        -> Result<CreateCheckpointResult, Self::Error>
    where
        C: CreateCheckpointContext;
}

#[derive(Debug, Clone, PartialEq)]
pub struct ReplaceRangeAsTickArgs {
    pub input: ReplaceRangeAsTickInput,
}

// ReplaceRangeAsTick forbidden surfaces: AstState, Diagnostics, GitWitness, UiState
pub trait ReplaceRangeAsTickContext:
    ReplaceRangeAsTickReadWorldlineSlot
    + ReplaceRangeAsTickWriteWorldlineSlot
    + ReplaceRangeAsTickReadBaseHeadSlot
    + ReplaceRangeAsTickReadTouchedRopeClosure
    + ReplaceRangeAsTickReadAffectedAnchorsClosure
    + ReplaceRangeAsTickCreateNewBlobSlot
    + ReplaceRangeAsTickCreateNewLeavesSlot
    + ReplaceRangeAsTickCreateNewBranchesSlot
    + ReplaceRangeAsTickCreateNextHeadSlot
    + ReplaceRangeAsTickCreateTickSlot
    + ReplaceRangeAsTickCreateReceiptSlot
    + ReplaceRangeAsTickUpdateWorldlineCanonicalHead
{
}
impl<T> ReplaceRangeAsTickContext for T where
    T: ReplaceRangeAsTickReadWorldlineSlot
        + ReplaceRangeAsTickWriteWorldlineSlot
        + ReplaceRangeAsTickReadBaseHeadSlot
        + ReplaceRangeAsTickReadTouchedRopeClosure
        + ReplaceRangeAsTickReadAffectedAnchorsClosure
        + ReplaceRangeAsTickCreateNewBlobSlot
        + ReplaceRangeAsTickCreateNewLeavesSlot
        + ReplaceRangeAsTickCreateNewBranchesSlot
        + ReplaceRangeAsTickCreateNextHeadSlot
        + ReplaceRangeAsTickCreateTickSlot
        + ReplaceRangeAsTickCreateReceiptSlot
        + ReplaceRangeAsTickUpdateWorldlineCanonicalHead
{
}

pub trait ReplaceRangeAsTickRewrite {
    type Error;

    fn apply<C>(
        &self,
        ctx: &mut C,
        args: ReplaceRangeAsTickArgs,
    ) -> Result<ReplaceRangeAsTickResult, Self::Error>
    where
        C: ReplaceRangeAsTickContext;
}
